spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_kata
    username: db_user
    password: db_pw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 5A7134743777397A24432646294A404E635266556A586E3272357538782F4125
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
